version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: @@CICDTEMPLATE_PROJECT_PREFIX@@-DOCKERHUB_USERNAME
    DOCKERHUB_PASSWORD: @@CICDTEMPLATE_PROJECT_PREFIX@@-DOCKERHUB_PASSWORD

phases:
  pre_build:
    commands:
      - docker --version
      - aws --version
      # Login to both DockerHub and Amazon ECR
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      # Build image
      - echo Docker image build started on $(date)
      # BUILDKIT var required to correctly load Dockerfile.dockerignore, but also generates a lot of debugging output
      - DOCKER_BUILDKIT=1 docker image build -f cicd/docker/commandbox/Dockerfile -t ${REPOSITORY_URI}:${IMAGE_TAG} .
      - echo Docker image build completed on $(date)
  post_build:
    commands:
      # Push image to ECR
      - echo Pushing the Docker image...
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      # Create output artifacts for next stage
      - echo Create deploy stage artifacts
      - printf '{"ImageURI":"%s"}' ${REPOSITORY_URI}:${IMAGE_TAG} > imageDetail.json
      - cp cicd/aws/templates/task-definition.json.tmpl task-definition.json
      - sed -i "s|CICDTEMPLATE_TASK_EXECUTION_ROLE_ARN|${TASKEXEC_ROLE}|g" task-definition.json
      - sed -i "s|CICDTEMPLATE_AWS_REGION|${AWS_REGION}|g" task-definition.json
      - cp cicd/aws/templates/appspec.yml appspec.yml
artifacts:
  files:
    - imageDetail.json
    - task-definition.json
    - appspec.yml