version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      # Get Commandbox
      - curl -fsSl https://downloads.ortussolutions.com/debs/gpg | apt-key add -
      - echo "deb https://downloads.ortussolutions.com/debs/noarch /" | tee -a /etc/apt/sources.list.d/commandbox.list
      - apt-get update && apt-get --assume-yes install apt-transport-https commandbox
  pre_build:
    commands:
      - aws --version
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - box version
  build:
    commands:
      # Build image
      - echo Docker image build started on $(date)
      # Required to correctly load Dockerfile.dockerignore
      - export DOCKER_BUILDKIT=1
      - docker image build -f cicd/docker/commandbox/Dockerfile -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo Docker image build completed on $(date)
      ### 
      ### 2022-03-18
      ### Now that production Dockerfile is using ENV BOX_SERVER_PROFILE=production the defaults path for running
      ### tests are administratively blocked.  This is great for security, but will require additional work if we want
      ### mount and run tests inside the prod-ready image at this point in the process.  For now commenting out and I
      ### would recommend running tests somewhere upstream prior to building the production container.
      ###
      ### # Run test container and call testbox runner
      ### - echo Running tests started on $(date)
      ### # 'tests' directory is excluded from the image so we volume mount it into the container.
      ### # (Also, we're making some assumptions about port number, ideally the container port would be sourced from `docker inspect`)
      ### - docker run -d --name codebuild_${ECR_REPO_NAME} -p 8080:8080 -v $(pwd)/tests:/app/tests $REPOSITORY_URI:$IMAGE_TAG
      ### # We install testbox inside our testing container after the image is built so that it doesn't get deployed.
      ### - docker exec -t -w /app codebuild_${ECR_REPO_NAME} box install testbox
      ### - timeout 60 bash -c 'until [[ "$(docker inspect --format {{.State.Health.Status}} codebuild_${ECR_REPO_NAME})" == "healthy" ]]; do echo -n .; sleep 3; done'
      ### - box testbox run runner="http://localhost:8080/tests/runner.cfm?method=runRemote" 
  post_build:
    commands:
      # Push image to ECR
      ### - echo Tests completed on $(date)
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      # Create output artifacts for next stage
      - echo Create deploy stage artifacts
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - cp cicd/aws/templates/task-definition.json.tmpl task-definition.json
      - sed -i "s|CICDTEMPLATE_TASK_EXECUTION_ROLE_ARN|$TASKEXEC_ROLE|g" task-definition.json
      - sed -i "s|CICDTEMPLATE_AWS_REGION|$AWS_REGION|g" task-definition.json
      - cp cicd/aws/templates/appspec.yml appspec.yml
artifacts:
  files:
    - imageDetail.json
    - task-definition.json
    - appspec.yml