version: "3"
services:
  app:
    build:
      context: .
      dockerfile: cicd/docker/commandbox/Dockerfile.dev
    environment:
      BOX_INSTALL: "true"
      cfconfig_adminPassword: "LocalAdmin1"
    ports:
      - 8080:8080
    volumes:
      - ./:/app